import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container:{
        flex:1,
        justifyContent:"center",
        alignItems:"center",
        width:"100%"
    },
    entryScreenLogo:{
        height:150,
        width:150
    },
    entryPageButton:{
        backgroundColor:"orange",
        alignItems:"center",
        width:"60%",
        padding:15,
        borderRadius:10,
    },
    entryPageText:{
        color:'white',
        fontWeight:'700',
        fontSize:16,
    },
    outlineButton:{
        backgroundColor:"white",
        marginTop:5,
        borderColor:"orange",
        borderWidth:2
    },
    outlineText:{
        color:'orange',
        fontWeight:'700',
        fontSize:16,
    },
    inputContainer:{
        width:"80%",
        justifyContent:"center",
        alignItems:"center"
    },
    authInput:{
        backgroundColor:"white",
        width:"100%",
        paddingHorizontal:15,
        paddingVertical:10,
        borderRadius:10,
        marginTop:5,
    },
    imageIcons:{
        height:50,
        width:50
    },
    headerAddBook:{
        flexDirection:"row",
        padding:15,
        justifyContent:"space-evenly",
        width:"100%"
    },
    input:{
        backgroundColor:"white",
        width:"70%",
        borderRadius:10,
        paddingHorizontal:15,
    },
    smallButton:{
        backgroundColor:"orange",
        alignItems:"center",
        padding:10,
        borderRadius:10,
    },
    scrollView:{
        width:"100%"
    },
    scrollViewContent:{
        alignItems:"center"
    },
    bookCard:{
        width:"90%",
        alignItems:"center"

    },
    bookDescription:{
        width:"100%",
        padding:15,
        backgroundColor:"#f5ad69",
        flexDirection:"row",
        justifyContent:"space-between",
        height:300
    },
    bookCardImage:{
        height:250,
        width:150,
    },
    bookDetails:{
        width:"50%"
    },
    bookText:{
        fontSize:14,
        fontStyle:"italic",
    },
    bookAuthor:{
        padding:2,
        borderRadius:"50%"        
    },
    bookCardCategory:{
        fontSize:15,
        color:"#b86a12",
        fontWeight:"bold"
    },
    readingBookContainer:{
        width:"90%",
        flexDirection:"row",
        backgroundColor:"#f5ad69",
        padding:10,
        borderRadius:10,
    },
    bookInfo:{
        padding:10,
    },
    bookPageContainer:{
        alignItems:"center",
        width:"100%"
    },
    bookPageDescription:{
        width:"90%",
    },
    bookPageText:{
        fontSize:20,
        fontStyle:"italic"
    },

})

export {styles}