import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container:{
        flex:1,
        justifyContent:"center",
        alignItems:"center",
        width:"100%"
    },
    entryScreenLogo:{
        height:150,
        width:150
    },
    entryPageButton:{
        backgroundColor:"orange",
        alignItems:"center",
        width:"60%",
        padding:15,
        borderRadius:10,
    },
    entryPageText:{
        color:'white',
        fontWeight:'700',
        fontSize:16,
    },
    outlineButton:{
        backgroundColor:"white",
        marginTop:5,
        borderColor:"orange",
        borderWidth:2
    },
    outlineText:{
        color:'orange',
        fontWeight:'700',
        fontSize:16,
    },
    inputContainer:{
        width:"80%",
        justifyContent:"center",
        alignItems:"center"
    },
    authInput:{
        backgroundColor:"white",
        width:"100%",
        paddingHorizontal:15,
        paddingVertical:10,
        borderRadius:10,
        marginTop:5,
    },
    imageIcons:{
        height:50,
        width:50
    },
    headerAddBook:{
        flexDirection:"row",
        padding:15,
        justifyContent:"space-evenly",
        width:"100%"
    },
    input:{
        backgroundColor:"white",
        width:"70%",
        borderRadius:10,
        paddingHorizontal:15,
    },
    smallButton:{
        backgroundColor:"orange",
        alignItems:"center",
        padding:10,
        borderRadius:10,
    },
    scrollView:{
        width:"100%",
    },
    scrollViewContent:{
        alignItems:"center",
        
        
    },
    bookCard:{
        width:"90%",
        alignItems:"center"

    },
    bookDescription:{
        width:"100%",
        padding:15,
        backgroundColor:"#f5ad69",
        flexDirection:"row",
        justifyContent:"space-between",
        height:300
    },
    bookCardImage:{
        height:250,
        width:150,
    },
    bookDetails:{
        width:"50%"
    },
    bookText:{
        fontSize:14,
        fontStyle:"italic",
    },
    bookAuthor:{
        padding:2,
        borderRadius:"50%"        
    },
    bookCardCategory:{
        fontSize:15,
        color:"#b86a12",
        fontWeight:"bold"
    },
    readingBookContainer:{
        width:"90%",
        flexDirection:"row",
        backgroundColor:"#f5ad69",
        padding:10,
        borderRadius:10,
    },
    bookInfo:{
        padding:10,
    },
    bookPageContainer:{
        alignItems:"center",
        width:"100%",
        backgroundColor:"#5c5654"
    },
    bookPageDescription:{
        width:"90%",
    },
    bookPageText:{
        fontSize:20,
        fontStyle:"italic"
    },
    weekContainer:{
        flexDirection:"row",
        width:"100%",
        justifyContent:"space-evenly",
        backgroundColor:"#5c5654",
    },
    dayContainer:{
        alignItems:"center",
    },
    dayNameContainer:{
        
    },
    dayNameText:{
        padding:10,
        fontSize:20,
        fontWeight:"bold",
    },
    dayNumberContainer:{
        backgroundColor:"gray",
        borderRadius:20
    },
    dayNumberText:{
        padding:10,
        fontSize:15,
        fontWeight:"bold",
    },
    todayText:{
        color:"#f7603e",
    },
    readContainer:{
        backgroundColor:"#ed8c66",
    },
    todayContainer:{
        borderWidth:2,
        borderColor:"#f7603e"
    },
    updateReadingForm:{
        flexDirection:"column",
        alignItems:"center",
        justifyContent:"flex-start",
        backgroundColor:"#5c5654",
        width:"90%",
        padding:15,
        borderRadius:10
    },
    dropdownBtnStyle:{
        backgroundColor:"#f5ad69",
        borderRadius:10,
    },
    dropdownBtnTextStyle:{
        fontWeight:'700',
        fontSize:16,
    },
    inputBookAdding:{
        width:150,
        height:30,
        backgroundColor:"gray",
        borderBottomWidth:2,
        fontSize:16
        
    },
    updateBtn:{
        backgroundColor:"orange",
        alignItems:"center",
        width:"60%",
        padding:5,
        borderRadius:10,
    },
    addBookManualyInput:{
        backgroundColor:"gray",
        height:30,
        fontSize:16,
        borderRadius:10
    }


})

export {styles}